import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logo from "public/assets/logo/logo.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Game Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-6">
        <nav className="mx-16 flex items-center justify-between">
          <Link href="/">
            <Image src={logo} alt="logo" />
          </Link>
          <ul className="flex w-fit min-w-[34rem] basis-2/5 items-center justify-between">
            <Link href="/" legacyBehavior passHref>
              <li className="basis-1/5 cursor-pointer rounded p-2 text-center transition-all hover:bg-purple-100">
                Account
              </li>
            </Link>
            <li className="basis-1/5 cursor-pointer rounded p-2 text-center transition-all hover:bg-purple-100">
              <Link href="/" legacyBehavior passHref>
                Logout
              </Link>
            </li>
            <Link href="/" legacyBehavior passHref>
              <li className="basis-1/5 cursor-pointer rounded p-2 text-center transition-all hover:bg-purple-100">
                Create Guide
              </li>
            </Link>
            <Link href="/" legacyBehavior passHref>
              <li className="basis-1/5 cursor-pointer rounded p-2 text-center transition-all hover:bg-purple-100">
                Login
              </li>
            </Link>
            <Link href="/" legacyBehavior passHref>
              <li className="basis-1/5 cursor-pointer rounded p-2 text-center transition-all hover:bg-purple-100">
                Sign Up
              </li>
            </Link>
          </ul>
        </nav>
      </main>
    </>
  );
}
